# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowAdd.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowAdd(object):
    def setupUi(self, WindowAdd):
        WindowAdd.setObjectName("WindowAdd")
        WindowAdd.resize(1200, 800)
        self.PhotoAdd = QtWidgets.QPushButton(WindowAdd)
        self.PhotoAdd.setGeometry(QtCore.QRect(20, 400, 151, 61))
        self.PhotoAdd.setObjectName("PhotoAdd")
        self.labelName = QtWidgets.QLabel(WindowAdd)
        self.labelName.setGeometry(QtCore.QRect(20, 20, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.Name = QtWidgets.QLineEdit(WindowAdd)
        self.Name.setGeometry(QtCore.QRect(20, 60, 441, 31))
        self.Name.setObjectName("Name")
        self.calendar = QtWidgets.QCalendarWidget(WindowAdd)
        self.calendar.setGeometry(QtCore.QRect(20, 140, 441, 236))
        self.calendar.setStyleSheet("alternate-background-color: rgb(0, 10, 202);\n"
"border-color: rgb(0, 0, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"background-color: rgb(232, 232, 116);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(255, 0, 0);")
        self.calendar.setObjectName("calendar")
        self.labelDate = QtWidgets.QLabel(WindowAdd)
        self.labelDate.setGeometry(QtCore.QRect(20, 100, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelDate.setFont(font)
        self.labelDate.setObjectName("labelDate")
        self.Period = QtWidgets.QComboBox(WindowAdd)
        self.Period.setGeometry(QtCore.QRect(20, 600, 321, 61))
        self.Period.setObjectName("Period")
        self.Period.addItem("")
        self.Period.addItem("")
        self.Period.addItem("")
        self.Period.setItemText(4, "")
        self.Comment = QtWidgets.QLineEdit(WindowAdd)
        self.Comment.setGeometry(QtCore.QRect(20, 520, 441, 51))
        self.Comment.setObjectName("Comment")
        self.labelComment = QtWidgets.QLabel(WindowAdd)
        self.labelComment.setGeometry(QtCore.QRect(20, 480, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelComment.setFont(font)
        self.labelComment.setObjectName("labelComment")
        self.BtnAdd = QtWidgets.QPushButton(WindowAdd)
        self.BtnAdd.setGeometry(QtCore.QRect(20, 680, 441, 31))
        self.BtnAdd.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.BtnAdd.setObjectName("BtnAdd")

        self.retranslateUi(WindowAdd)
        QtCore.QMetaObject.connectSlotsByName(WindowAdd)

    def retranslateUi(self, WindowAdd):
        _translate = QtCore.QCoreApplication.translate
        WindowAdd.setWindowTitle(_translate("WindowAdd", "Добавление"))
        self.PhotoAdd.setText(_translate("WindowAdd", "Прикрепить фото"))
        self.labelName.setText(_translate("WindowAdd", "Название:"))
        self.Name.setPlaceholderText(_translate("WindowAdd", "Введите название уведомления"))
        self.labelDate.setText(_translate("WindowAdd", "Дата окончания:"))
        self.Period.setItemText(0, _translate("WindowAdd", "Выберите периодичность уведомлений"))
        self.Period.setItemText(1, _translate("WindowAdd", "Easy"))
        self.Period.setItemText(2, _translate("WindowAdd", "Hard"))
        self.Comment.setPlaceholderText(_translate("WindowAdd", "Введиие комментарий к уведомлению"))
        self.labelComment.setText(_translate("WindowAdd", "Комментарий"))
        self.BtnAdd.setText(_translate("WindowAdd", "Добавить"))
