# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowBasic.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendar.setGeometry(QtCore.QRect(30, 200, 511, 531))
        self.calendar.setStyleSheet("alternate-background-color: rgb(0, 10, 202);\n"
"border-color: rgb(0, 0, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"background-color: rgb(232, 232, 116);\n"
"color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(255, 0, 0);")
        self.calendar.setObjectName("calendar")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(30, 70, 100, 30))
        self.btn_add.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.btn_add.setObjectName("btn_add")
        self.labelChoice = QtWidgets.QLabel(self.centralwidget)
        self.labelChoice.setGeometry(QtCore.QRect(30, 20, 450, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelChoice.sizePolicy().hasHeightForWidth())
        self.labelChoice.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelChoice.setFont(font)
        self.labelChoice.setObjectName("labelChoice")
        self.copyright = QtWidgets.QLabel(self.centralwidget)
        self.copyright.setGeometry(QtCore.QRect(1080, 700, 121, 101))
        self.copyright.setTextFormat(QtCore.Qt.PlainText)
        self.copyright.setScaledContents(True)
        self.copyright.setObjectName("copyright")
        self.labelCal = QtWidgets.QLabel(self.centralwidget)
        self.labelCal.setGeometry(QtCore.QRect(160, 150, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelCal.setFont(font)
        self.labelCal.setObjectName("labelCal")
        self.labelDay = QtWidgets.QLabel(self.centralwidget)
        self.labelDay.setGeometry(QtCore.QRect(680, 20, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelDay.setFont(font)
        self.labelDay.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelDay.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDay.setObjectName("labelDay")
        self.labelPhoto = QtWidgets.QLabel(self.centralwidget)
        self.labelPhoto.setGeometry(QtCore.QRect(570, 320, 611, 391))
        self.labelPhoto.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.labelPhoto.setObjectName("labelPhoto")
        self.Targets = QtWidgets.QComboBox(self.centralwidget)
        self.Targets.setGeometry(QtCore.QRect(570, 60, 611, 31))
        self.Targets.setObjectName("Targets")
        self.labelComment = QtWidgets.QLabel(self.centralwidget)
        self.labelComment.setGeometry(QtCore.QRect(580, 110, 601, 201))
        self.labelComment.setStyleSheet("background-color: rgb(255, 251, 249);")
        self.labelComment.setObjectName("labelComment")
        self.btnOpenPhoto = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenPhoto.setGeometry(QtCore.QRect(560, 730, 511, 31))
        self.btnOpenPhoto.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.btnOpenPhoto.setObjectName("btnOpenPhoto")
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(160, 70, 100, 30))
        self.btn_delete.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.btn_delete.setObjectName("btn_delete")
        MainWindow.setCentralWidget(self.centralwidget)
        self.labelError = QtWidgets.QLabel(self.centralwidget)
        self.labelError.move(10, 10)
        self.labelError.hide()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Notification Homework"))
        self.btn_add.setText(_translate("MainWindow", "Добавить"))
        self.labelChoice.setText(_translate("MainWindow", "Выберите действие с уведомлением"))
        self.copyright.setText(_translate("MainWindow", "© 2020 AFD333"))
        self.labelCal.setText(_translate("MainWindow", "Выберите день для просмотра"))
        self.labelDay.setText(_translate("MainWindow", "Просмотр дня:"))
        self.labelPhoto.setText(_translate("MainWindow", "ФОТО"))
        self.labelComment.setText(_translate("MainWindow", "КОММЕНТАРИЙ"))
        self.btnOpenPhoto.setText(_translate("MainWindow", "Открыть фото"))
        self.btn_delete.setText(_translate("MainWindow", "Удалить"))
